"use client";
import "./globals.css";
import localFont from "next/font/local";

import Header from "@/components/common/layout/header";
import { AnimatePresence } from "framer-motion";
import React, { useEffect, useState } from "react";
import Preloader from "@/app/components/preloader";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };
// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };
import { ScrollerMotion } from "scroller-motion";
import Footer from "@/components/common/layout/footer";

const nbInternational = localFont({
  src: [
    {
      path: "./fonts/NBInternational-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/NBInternational-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/NBInternational-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-nb-international",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Set a timeout to hide the loading screen after 3 seconds
    const timer = setTimeout(() => {
      setLoading(false);
    }, 3500);

    return () => clearTimeout(timer);
  }, []);

  return (
    <html lang="en">
      <body className={`${nbInternational.variable} antialiased`}>
        {/* <AnimatePresence> */}
        {/* {loading ? ( */}
        {/* // <Preloader key={"preloader"} /> */}
        {/* ) : ( */}
        <>
          <Header />
          {children}
          <Footer />
        </>
        {/* )} */}
        {/* </AnimatePresence> */}
      </body>
    </html>
  );
}
