import "./globals.css";
import localFont from "next/font/local";

import Header from "@/components/common/layout/header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import { ScrollerMotion } from "scroller-motion";

const nbInternational = localFont({
  src: [
    {
      path: "./fonts/NBInternational-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/NBInternational-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/NBInternational-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-nb-international",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${nbInternational.variable} antialiased`}>
        {/* <Header /> */}
        {children}
      </body>
    </html>
  );
}
